/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankEntry {
  'year' : bigint,
  'usedAmount' : number,
  'routeId' : string,
  'bankedAmount' : number,
}
export interface ComplianceResult {
  'energyInScope' : number,
  'isCompliant' : boolean,
  'complianceBalance' : number,
}
export interface PoolMember {
  'cb_after' : number,
  'cb_before' : number,
  'routeId' : string,
}
export interface PoolRecord {
  'members' : Array<PoolMember>,
  'valid' : boolean,
  'timestamp' : bigint,
  'poolSum' : number,
  'poolId' : string,
}
export interface Route {
  'vesselType' : string,
  'year' : bigint,
  'fuelConsumption' : number,
  'distance' : number,
  'isBaseline' : boolean,
  'routeId' : string,
  'fuelType' : string,
  'ghgIntensity' : number,
  'totalEmissions' : number,
}
export interface _SERVICE {
  'applyBankedSurplus' : ActorMethod<[string, number], undefined>,
  'bankSurplus' : ActorMethod<[string], undefined>,
  'createPool' : ActorMethod<[Array<string>], undefined>,
  'getAllBankEntries' : ActorMethod<[], Array<BankEntry>>,
  'getBankEntry' : ActorMethod<[string], [] | [BankEntry]>,
  'getBaseline' : ActorMethod<[], [] | [Route]>,
  'getComplianceBalance' : ActorMethod<[string], ComplianceResult>,
  'getPools' : ActorMethod<[], Array<PoolRecord>>,
  'getRoutes' : ActorMethod<[], Array<Route>>,
  'init' : ActorMethod<[], undefined>,
  'setBaseline' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];