/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BankEntry = IDL.Record({
  'year' : IDL.Nat,
  'usedAmount' : IDL.Float64,
  'routeId' : IDL.Text,
  'bankedAmount' : IDL.Float64,
});
export const Route = IDL.Record({
  'vesselType' : IDL.Text,
  'year' : IDL.Nat,
  'fuelConsumption' : IDL.Float64,
  'distance' : IDL.Float64,
  'isBaseline' : IDL.Bool,
  'routeId' : IDL.Text,
  'fuelType' : IDL.Text,
  'ghgIntensity' : IDL.Float64,
  'totalEmissions' : IDL.Float64,
});
export const ComplianceResult = IDL.Record({
  'energyInScope' : IDL.Float64,
  'isCompliant' : IDL.Bool,
  'complianceBalance' : IDL.Float64,
});
export const PoolMember = IDL.Record({
  'cb_after' : IDL.Float64,
  'cb_before' : IDL.Float64,
  'routeId' : IDL.Text,
});
export const PoolRecord = IDL.Record({
  'members' : IDL.Vec(PoolMember),
  'valid' : IDL.Bool,
  'timestamp' : IDL.Int,
  'poolSum' : IDL.Float64,
  'poolId' : IDL.Text,
});

export const idlService = IDL.Service({
  'applyBankedSurplus' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'bankSurplus' : IDL.Func([IDL.Text], [], []),
  'createPool' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'getAllBankEntries' : IDL.Func([], [IDL.Vec(BankEntry)], ['query']),
  'getBankEntry' : IDL.Func([IDL.Text], [IDL.Opt(BankEntry)], ['query']),
  'getBaseline' : IDL.Func([], [IDL.Opt(Route)], ['query']),
  'getComplianceBalance' : IDL.Func([IDL.Text], [ComplianceResult], ['query']),
  'getPools' : IDL.Func([], [IDL.Vec(PoolRecord)], ['query']),
  'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'init' : IDL.Func([], [], []),
  'setBaseline' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BankEntry = IDL.Record({
    'year' : IDL.Nat,
    'usedAmount' : IDL.Float64,
    'routeId' : IDL.Text,
    'bankedAmount' : IDL.Float64,
  });
  const Route = IDL.Record({
    'vesselType' : IDL.Text,
    'year' : IDL.Nat,
    'fuelConsumption' : IDL.Float64,
    'distance' : IDL.Float64,
    'isBaseline' : IDL.Bool,
    'routeId' : IDL.Text,
    'fuelType' : IDL.Text,
    'ghgIntensity' : IDL.Float64,
    'totalEmissions' : IDL.Float64,
  });
  const ComplianceResult = IDL.Record({
    'energyInScope' : IDL.Float64,
    'isCompliant' : IDL.Bool,
    'complianceBalance' : IDL.Float64,
  });
  const PoolMember = IDL.Record({
    'cb_after' : IDL.Float64,
    'cb_before' : IDL.Float64,
    'routeId' : IDL.Text,
  });
  const PoolRecord = IDL.Record({
    'members' : IDL.Vec(PoolMember),
    'valid' : IDL.Bool,
    'timestamp' : IDL.Int,
    'poolSum' : IDL.Float64,
    'poolId' : IDL.Text,
  });
  
  return IDL.Service({
    'applyBankedSurplus' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'bankSurplus' : IDL.Func([IDL.Text], [], []),
    'createPool' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'getAllBankEntries' : IDL.Func([], [IDL.Vec(BankEntry)], ['query']),
    'getBankEntry' : IDL.Func([IDL.Text], [IDL.Opt(BankEntry)], ['query']),
    'getBaseline' : IDL.Func([], [IDL.Opt(Route)], ['query']),
    'getComplianceBalance' : IDL.Func(
        [IDL.Text],
        [ComplianceResult],
        ['query'],
      ),
    'getPools' : IDL.Func([], [IDL.Vec(PoolRecord)], ['query']),
    'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'init' : IDL.Func([], [], []),
    'setBaseline' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };