/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PoolRecord {
    members: Array<PoolMember>;
    valid: boolean;
    timestamp: bigint;
    poolSum: number;
    poolId: string;
}
export interface ComplianceResult {
    energyInScope: number;
    isCompliant: boolean;
    complianceBalance: number;
}
export interface PoolMember {
    cb_after: number;
    cb_before: number;
    routeId: string;
}
export interface BankEntry {
    year: bigint;
    usedAmount: number;
    routeId: string;
    bankedAmount: number;
}
export interface Route {
    vesselType: string;
    year: bigint;
    fuelConsumption: number;
    distance: number;
    isBaseline: boolean;
    routeId: string;
    fuelType: string;
    ghgIntensity: number;
    totalEmissions: number;
}
export interface backendInterface {
    applyBankedSurplus(routeId: string, amount: number): Promise<void>;
    bankSurplus(routeId: string): Promise<void>;
    createPool(routeIds: Array<string>): Promise<void>;
    getAllBankEntries(): Promise<Array<BankEntry>>;
    getBankEntry(routeId: string): Promise<BankEntry | null>;
    getBaseline(): Promise<Route | null>;
    getComplianceBalance(routeId: string): Promise<ComplianceResult>;
    getPools(): Promise<Array<PoolRecord>>;
    getRoutes(): Promise<Array<Route>>;
    init(): Promise<void>;
    setBaseline(routeId: string): Promise<void>;
}
import type { BankEntry as _BankEntry, Route as _Route } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyBankedSurplus(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyBankedSurplus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyBankedSurplus(arg0, arg1);
            return result;
        }
    }
    async bankSurplus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bankSurplus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bankSurplus(arg0);
            return result;
        }
    }
    async createPool(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPool(arg0);
            return result;
        }
    }
    async getAllBankEntries(): Promise<Array<BankEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankEntries();
            return result;
        }
    }
    async getBankEntry(arg0: string): Promise<BankEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankEntry(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankEntry(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBaseline(): Promise<Route | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBaseline();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBaseline();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplianceBalance(arg0: string): Promise<ComplianceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplianceBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplianceBalance(arg0);
            return result;
        }
    }
    async getPools(): Promise<Array<PoolRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPools();
            return result;
        }
    }
    async getRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutes();
            return result;
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async setBaseline(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBaseline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBaseline(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BankEntry]): BankEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Route]): Route | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
